# Generated by Django 4.1.5 on 2023-01-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('debt', models.FloatField(verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('land', models.CharField(max_length=50, unique=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='Брэнд')),
                ('release_date', models.DateTimeField(blank=True, verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ts_elektrik.basemodel')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
            bases=('ts_elektrik.basemodel',),
        ),
        migrations.CreateModel(
            name='Retail_network',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ts_elektrik.basemodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_elektrik.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
            bases=('ts_elektrik.basemodel',),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_elektrik.contacts', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_elektrik.products', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='Sole_trader',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ts_elektrik.basemodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ts_elektrik.retail_network', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
            bases=('ts_elektrik.basemodel',),
        ),
    ]
