# Generated by Django 4.1.5 on 2023-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_elektrik', '0002_alter_contacts_email_alter_contacts_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(blank=True, verbose_name='Дата выхода на рынок'),
        ),
    ]
